name: Read Json as input

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
        json_input:
          description: 'JSON input'
          required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: set environment
        run: |
            python setenvfromdict.py "${{ github.event.inputs.json_input }}"
            echo $KEY1
            echo $key1
            echo "key1=valueset1" >> $GITHUB_ENV
    
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          
      - name: Print env
        run: |
          echo "Environment variables set"
          echo "KEY1: $KEY1"
          echo "KEY2: $KEY2"
          env